### ISSUE TITLE
Please add support for notifications

### ISSUE THREAD

**Issue by adhithyasrinivasan** [jwisniewski/android-developer-assistant#1]
Dev assistant cannot operate on notifications. Please add support

**Comment by jwisniewski** [comment]
At the moment, Developer Assistant is able to inspect views attached to the Activity window. Notifications are displayed by the system on a different layer, I need yet to investigate if it's even possible to inspect them. Thank you for the hint!

**Comment by jwisniewski** [comment]
@adhithyasrinivasan unfortunately the existing Android API (investigated on API v28) doesn't allow to inspect content of the Notification Center, including content of the Notifications displayed in it.
