### ISSUE TITLE
Opening app if I have no navigation buttons.

### ISSUE THREAD

**Issue by neutralme** [jwisniewski/android-developer-assistant#9]
Is there any voice shortcuts to open apps if there is no navigation buttons in my device.
![IMG_20210426_201532](https://user-images.githubusercontent.com/83157357/116100048-4b316680-a6cc-11eb-9170-1ead88279466.jpg)

**Comment by jwisniewski** [comment]
It depends on device. Sometimes even on device settings. Generally you would need to learn how to invoke "assist app" on your device.

The most common cases are described in Developer Assistant. Open the app. Click SHOW ALTERNATIVES on the following screen:
![Screenshot_20200705-113746_Developer Assistant](https://user-images.githubusercontent.com/3899440/117356534-21d6be80-aeb4-11eb-850c-6f182ab77393.jpg)

Cases for some devices are also described in:
https://github.com/jwisniewski/android-developer-assistant/wiki/How-to-setup:-common-problems

I hope I helped a bit, did I? ;)

**Comment by Illist** [comment]
+13145743786
